version: "2"
services:
  notebook:
    image: jupyter/minimal-notebook
    restart: always
    ports:
      - "8888:8888"
    volumes:
      - ./work/:/home/jovyan
    container_name: notebook-container
